package net.raphaelgf11.ilo3manager.vpn

/**
 * A parsed WireGuard configuration, as found in a standard `wg-quick` .conf file.
 *
 * Only the fields this app can act on are modelled; the raw text is what gets stored, so anything
 * not represented here survives a round trip untouched.
 */
data class WireGuardConfig(
    val privateKey: String,
    val addresses: List<String>,
    val dnsServers: List<String>,
    val mtu: Int?,
    val peerPublicKey: String,
    val presharedKey: String?,
    val endpoint: String,
    val allowedIps: List<String>,
    val persistentKeepaliveSeconds: Int?,
) {
    /** Endpoint host without the port, for display. */
    val endpointHost: String get() = endpoint.substringBeforeLast(':', endpoint)
}

class WireGuardConfigException(message: String) : IllegalArgumentException(message)

/**
 * Reads the `wg-quick` INI-like format: `[Interface]` and `[Peer]` sections of `Key = Value`
 * lines. Deliberately lenient about whitespace, comments and key case, since these files are
 * routinely hand-edited or generated by different tools, but strict about the handful of fields a
 * tunnel cannot be established without.
 */
object WireGuardConfigParser {

    fun parse(text: String): WireGuardConfig {
        var section = ""
        val interfaceValues = mutableMapOf<String, String>()
        val peerValues = mutableMapOf<String, String>()

        for (rawLine in text.lines()) {
            val line = rawLine.substringBefore('#').substringBefore(';').trim()
            if (line.isEmpty()) continue
            if (line.startsWith("[") && line.endsWith("]")) {
                section = line.trim('[', ']').trim().lowercase()
                continue
            }
            val separator = line.indexOf('=')
            if (separator <= 0) continue
            val key = line.substring(0, separator).trim().lowercase()
            val value = line.substring(separator + 1).trim()
            when (section) {
                "interface" -> interfaceValues[key] = value
                // Only the first peer is used: this app tunnels to one management network, and
                // supporting several would mean implementing per-peer routing decisions.
                "peer" -> peerValues.putIfAbsent(key, value)
            }
        }

        val privateKey = interfaceValues["privatekey"]
            ?: throw WireGuardConfigException("PrivateKey manquant dans la section [Interface].")
        val address = interfaceValues["address"]
            ?: throw WireGuardConfigException("Address manquant dans la section [Interface].")
        val peerPublicKey = peerValues["publickey"]
            ?: throw WireGuardConfigException("PublicKey manquant dans la section [Peer].")
        val endpoint = peerValues["endpoint"]
            ?: throw WireGuardConfigException("Endpoint manquant dans la section [Peer].")
        val allowedIps = peerValues["allowedips"]
            ?: throw WireGuardConfigException("AllowedIPs manquant dans la section [Peer].")

        return WireGuardConfig(
            privateKey = privateKey,
            addresses = splitList(address),
            dnsServers = interfaceValues["dns"]?.let(::splitList).orEmpty(),
            mtu = interfaceValues["mtu"]?.toIntOrNull(),
            peerPublicKey = peerPublicKey,
            presharedKey = peerValues["presharedkey"],
            endpoint = endpoint,
            allowedIps = splitList(allowedIps),
            persistentKeepaliveSeconds = peerValues["persistentkeepalive"]?.toIntOrNull(),
        )
    }

    private fun splitList(value: String): List<String> =
        value.split(',').map { it.trim() }.filter { it.isNotEmpty() }
}
